

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      install-tomcat-Server:
        description: 'install-Server'
        type: boolean
        required: true
      configuration-setup:
        description: 'configuration-setup'
        type: boolean
        required: true
      Deploy-latest-code:
        description: 'Deploy-latest-code'
        type: boolean
        required: true
      restart-application:
        description: 'restart-application'
        type: boolean
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "value from the user" ${{ github.event.inputs.varribe1 }}
  control-job:
    runs-on: ubuntu-latest
    if: ${{inputs.install-tomcat-Server }}
    steps:
      - name: install-tomcat-server
        run: echo "nstalling tomcat server"
  Deploy-latest-code:
    runs-on: ubuntu-latest    
    if: ${{inputs.Deploy-latest-code }}
    steps:
      - name: configuration-setup
        run: echo "configuration-setup"
  

      
